services:
  app:
    image: next-app:latest
    restart: always
    networks:
      - caddy

  caddy:
    image: caddy:builder-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - caddy

networks:
  caddy:
    driver: bridge

volumes:
  caddy_data:
