name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода
      - uses: actions/checkout@v4

      # Установка Bun
      - name: Установка Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "export PATH=\"$HOME/.bun/bin:$PATH\"" >> $GITHUB_ENV

      # Установка зависимостей
      - name: Установка зависимостей
        run: ~/.bun/bin/bun install

      # Сборка приложения
      - name: Сборка приложения
        run: ~/.bun/bin/bun run build

      # Настройка SSH-агента для разблокировки ключа с passphrase
      - name: Настройка SSH-агента
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.SERVER_PASSPHRASE }}

      # Деплой на сервер через SSH
      - name: Деплой на сервер
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 22
          script: |
            cd /path/to/project
            git pull origin main
            docker compose down
            docker compose up --build -d
