name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t next-app:latest .
        docker save -o image.tar next-app:latest
        chmod 644 image.tar


    - name: Transfer artifacts
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "image.tar,docker-compose.yml,Caddyfile"
        target: "~/next-app"
    - name: Deploy on server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd ~/next-app
          sudo docker load -i image.tar
          sudo docker compose up -d --scale app=2 --no-recreate
          sleep 10
          sudo docker compose up -d --force-recreate
          sudo docker compose exec caddy caddy reload --config /etc/caddy/Caddyfile
          sudo docker compose rm app --force --stop -v
