name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода
      - uses: actions/checkout@v4

      # Установка Bun
      - name: Установка Bun
        run: curl -fsSL https://bun.sh/install | bash

      # Установка зависимостей и сборка
      - name: Установка зависимостей
        run: bun install
        
      - name: Сборка приложения
        run: bun run build
        
      # Деплой на сервер через SSH
      - name: Деплой на сервер
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          script: |
            cd /path/to/project
            git pull origin main
            docker compose down
            docker compose up --build -d
