name: Zero Downtime Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t next-app:latest .
        docker save -o image.tar next-app:latest
        chmod 644 image.tar

    - name: Transfer files via SCP
      uses: appleboy/scp-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "image.tar,docker-compose.yml,Caddyfile"
        target: "~/next-app"
        strip_components: 1

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd ~/next-app
          sudo docker load -i image.tar
          sudo docker compose -f ./docker-compose.yml up -d --scale app=2 --no-recreate
          sleep 15
          sudo docker compose -f ./docker-compose.yml up -d --force-recreate
          sudo docker compose -f ./docker-compose.yml exec caddy caddy reload
          sudo docker image prune -af
